context:
  version: "0.24.0"

package:
  name: ironclaw
  version: ${{ version }}

source:
  url: https://github.com/nearai/ironclaw/archive/refs/tags/ironclaw-v${{ version }}.tar.gz
  sha256: b920af1ab1d2c4753cd275b0813b958df7db650de2c951339a649f733e9a132b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - ironclaw --version

about:
  homepage: https://github.com/nearai/ironclaw
  summary: IronClaw is OpenClaw inspired implementation in Rust focused on privacy and security
  description: |
    IronClaw is OpenClaw inspired implementation in Rust focused on privacy and security
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  documentation: https://docs.ironclaw.com
  repository: https://github.com/nearai/ironclaw

extra:
  recipe-maintainers:
    - yuikisaito
